version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html
  - source: scripts/start_server.sh
    destination: /home/ec2-user/scripts
hooks:
  BeforeInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
