version: 0.2
phases:
  pre_build:
    commands:
      - echo "Starting build process..."
      - echo "Build started on $(date)"
      - echo "Preparing build environment..."
  build:
    commands:
      - echo "Building the application..."
      - echo "Copying files for deployment..."
      - echo "Build process completed successfully"
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Preparing artifacts for deployment..."
      - echo "Build artifacts ready for deployment"
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/*
  name: myapp-$(date +%Y-%m-%d)
